//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatEle2PDF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatEle2PDF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet
        ///	version=&quot;1.1&quot;
        ///	xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///	xmlns:b=&quot;http://www.fatturapa.gov.it/sdi/fatturapa/v1.1&quot;
        ///	xmlns:c=&quot;http://www.fatturapa.gov.it/sdi/fatturapa/v1.0&quot;
        ///	xmlns:a=&quot;http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2&quot;
        ///	xmlns:d=&quot;http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;html&quot; /&gt;
        ///  &lt;xsl:decimal-format name=&quot;euro&quot; decimal-separator=&quot;,&quot; grouping-separator=&quot;.&quot;/&gt;
        ///
        ///  &lt;xsl:template name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FoglioStile {
            get {
                return ResourceManager.GetString("FoglioStile", resourceCulture);
            }
        }
    }
}
